### ISSUE TITLE
Not compatible with HA 2024.1.0

### ISSUE THREAD

**Issue by YahyaAlfayad** [barban-dev/homeassistant-midea-dehumidifier#64] opened 2024-01-04 18:31 UTC
After updating to HA 2024.1.0, the midea-dehumidifier component stopped working with the following log message:

```
Error while setting up midea_dehumidifier platform for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 217, in state_attributes
    if HumidifierEntityFeature.MODES in self.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

**Comment by cannondale0815** [comment] 2024-01-05 01:54
It's not being maintained anymore for a while unfortunately

**Comment by fabrizioromanelli** [comment] 2024-01-05 10:52
I made the modifications to work with HA2024.1.0.
I don't think they will accept to merge my changes in their branch soon, so, if you're interested, just ping me to make it work back.

**Comment by pinterd** [comment] 2024-01-05 13:47
> I made the modifications to work with HA2024.1.0. I don't think they will accept to merge my changes in their branch soon, so, if you're interested, just ping me to make it work back.

Hello,
do you have a solution?

**Comment by fabrizioromanelli** [comment] 2024-01-05 13:54
> > I made the modifications to work with HA2024.1.0. I don't think they will accept to merge my changes in their branch soon, so, if you're interested, just ping me to make it work back.
> 
> Hello, do you have a solution?

Yes, just go to the forked project in my GitHub: https://github.com/fabrizioromanelli/homeassistant-midea-dehumidifier
And replace humidifier.py and sensor.py in your home assistant installation with the ones provided on my page, restart HA and it'll work!

**Comment by pinterd** [comment] 2024-01-05 13:56
> > > I made the modifications to work with HA2024.1.0. I don't think they will accept to merge my changes in their branch soon, so, if you're interested, just ping me to make it work back.
> > 
> > 
> > Hello, do you have a solution?
> 
> Yes, just go to the forked project in my GitHub: https://github.com/fabrizioromanelli/homeassistant-midea-dehumidifier And replace humidifier.py and sensor.py in your home assistant installation with the ones provided on my page, restart HA and it'll work!

Thank you very much, I will try it this weekend

**Comment by YahyaAlfayad** [comment] 2024-01-05 15:40
@fabrizioromanelli , I've just copied your fix and it works! Thanks a lot!

**Comment by YahyaAlfayad** [comment] 2024-01-05 17:14
FYI, [HA 2024.1.1](https://www.home-assistant.io/blog/2024/01/03/release-20241/#release-202411---january-5) fixed the backwards compatibility for humidifier supported_features

**Comment by fabrizioromanelli** [comment] 2024-01-05 18:18
> FYI, [HA 2024.1.1](https://www.home-assistant.io/blog/2024/01/03/release-20241/#release-202411---january-5) fixed the backwards compatibility for humidifier supported_features

Yes, I tested it but it didn't solve the problem, so the only way is to use the fixes I suggested.

**Comment by barban-dev** [comment] 2024-01-05 18:33
Hi all, I created release v1.04 by including changes from @fabrizioromanelli (grazie Fabrizio!)
Please provide feedbacks that this new release works as expected.

**Comment by fabrizioromanelli** [comment] 2024-01-05 18:53
> Hi all, I created release v1.04 by including changes from @fabrizioromanelli (grazie Fabrizio!) Please provide feedbacks that this new release works as expected.

Great @barban-dev! Thanks a lot. I didn't make a pull request as I thought your repo was not updated anymore! 😅

**Comment by barban-dev** [comment] 2024-01-05 19:38
> > Hi all, I created release v1.04 by including changes from @fabrizioromanelli (grazie Fabrizio!) Please provide feedbacks that this new release works as expected.
> 
> Great @barban-dev! Thanks a lot. I didn't make a pull request as I thought your repo was not updated anymore! 😅
I am trying to maintain the repo at least in a working state: pull requests are welcome!. 
BR

**Comment by 5a2v0** [comment] 2024-01-06 07:10
Hi, my ha notify me 2024.1.1 version and when i installed It the integrations starts againt to work.

After this ha notify me the 1.04 version and i installed It too but now i get errors and the integrations doesnt work anymore:

`Logger: homeassistant.loader
Source: loader.py:842
First occurred: 5 gennaio 2024 alle ore 22:32:03 (2 occurrences)
Last logged: 5 gennaio 2024 alle ore 22:32:03

Unexpected exception importing platform custom_components.midea_dehumidifier.sensor
Unexpected exception importing platform custom_components.midea_dehumidifier.humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/midea_dehumidifier/sensor.py", line 54
    	self._device_class = SensorDeviceClass.HUMIDITY
    ^
TabError: inconsistent use of tabs and spaces in indentation
`

**Comment by ptgomes** [comment] 2024-01-06 18:05
Also

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 17:54:13 (2 occurrences)
Last logged: 17:54:14

Unexpected exception importing platform custom_components.midea_dehumidifier.humidifier
Unexpected exception importing platform custom_components.midea_dehumidifier.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/midea_dehumidifier/humidifier.py", line 187
    	self._device_class = HumidifierDeviceClass.DEHUMIDIFIER
    ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by 5a2v0** [comment] 2024-01-06 18:16
> Also
> 
> Logger: homeassistant.loader Source: loader.py:842 First occurred: 17:54:13 (2 occurrences) Last logged: 17:54:14
> 
> Unexpected exception importing platform custom_components.midea_dehumidifier.humidifier Unexpected exception importing platform custom_components.midea_dehumidifier.sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform cache[full_name] = self._import_platform(platform_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 936, in exec_module File "", line 1074, in get_code File "", line 1004, in source_to_code File "", line 241, in _call_with_frames_removed File "/config/custom_components/midea_dehumidifier/humidifier.py", line 187 self._device_class = HumidifierDeviceClass.DEHUMIDIFIER ^ TabError: inconsistent use of tabs and spaces in indentation

I did two Pull Request that correct this errore and the one that i reported in the post above. I tested It on my ha with success

**Comment by ptgomes** [comment] 2024-01-06 18:24
It stopped working when i updated the integration on hacs. What else its needed?

**Comment by barban-dev** [comment] 2024-01-06 18:28
> > Also
> > Logger: homeassistant.loader Source: loader.py:842 First occurred: 17:54:13 (2 occurrences) Last logged: 17:54:14
> > Unexpected exception importing platform custom_components.midea_dehumidifier.humidifier Unexpected exception importing platform custom_components.midea_dehumidifier.sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform cache[full_name] = self._import_platform(platform_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 936, in exec_module File "", line 1074, in get_code File "", line 1004, in source_to_code File "", line 241, in _call_with_frames_removed File "/config/custom_components/midea_dehumidifier/humidifier.py", line 187 self._device_class = HumidifierDeviceClass.DEHUMIDIFIER ^ TabError: inconsistent use of tabs and spaces in indentation
> 
> I did two Pull Request that correct this errore and the one that i reported in the post above. I tested It on my ha with success

Merged: please try v.104 patched release

**Comment by ptgomes** [comment] 2024-01-07 17:40
I've replaced humidifier.py and sensor.py. No joy.

**Comment by LeoWinterDE** [comment] 2024-01-07 20:56
Running the latested version `1.04` from HACS on `Core 2024.1.2, Supervisor 2023.12.0, Operating System 11.3`:

![Screenshot 2024-01-07 215541](https://github.com/barban-dev/homeassistant-midea-dehumidifier/assets/1300141/a1cedd65-7df6-4131-b5fc-b6f9d0b7c05b)

![Screenshot 2024-01-07 215118](https://github.com/barban-dev/homeassistant-midea-dehumidifier/assets/1300141/60c9eca3-324e-4270-a0bc-f0990bfc8462)

```
 Logger: homeassistant.setup
Source: setup.py:403
First occurred: 21:49:37 (2 occurrences)
Last logged: 21:49:40

    Unable to prepare setup for platform 'midea_dehumidifier.sensor': Platform not found (Exception importing custom_components.midea_dehumidifier.sensor).
    Unable to prepare setup for platform 'midea_dehumidifier.humidifier': Platform not found (Exception importing custom_components.midea_dehumidifier.humidifier).
```

```
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 21:49:37 (2 occurrences)
Last logged: 21:49:40

    Unexpected exception importing platform custom_components.midea_dehumidifier.sensor
    Unexpected exception importing platform custom_components.midea_dehumidifier.humidifier

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/midea_dehumidifier/sensor.py", line 54
    	self._device_class = SensorDeviceClass.HUMIDITY
    ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by shvirik** [comment] 2024-01-10 08:23
> > > I made the modifications to work with HA2024.1.0. I don't think they will accept to merge my changes in their branch soon, so, if you're interested, just ping me to make it work back.
> > 
> > 
> > Hello, do you have a solution?
> 
> Yes, just go to the forked project in my GitHub: https://github.com/fabrizioromanelli/homeassistant-midea-dehumidifier And replace humidifier.py and sensor.py in your home assistant installation with the ones provided on my page, restart HA and it'll work!

In my installation (VM) it works properly!!! 

THX!!!

**Comment by domerich** [comment] 2024-01-12 12:04
> > > I made the modifications to work with HA2024.1.0. I don't think they will accept to merge my changes in their branch soon, so, if you're interested, just ping me to make it work back.
> > 
> > 
> > Hello, do you have a solution?
> 
> Yes, just go to the forked project in my GitHub: https://github.com/fabrizioromanelli/homeassistant-midea-dehumidifier And replace humidifier.py and sensor.py in your home assistant installation with the ones provided on my page, restart HA and it'll work!

that works mille grazie

**Comment by ptgomes** [comment] 2024-01-12 13:06
> > > > > > I made the modifications to work with HA2024.1.0. I don't think they will accept to merge my changes in their branch soon, so, if you're interested, just ping me to make it work back.
> > > > > 
> > > > > 
> > > > > Hello, do you have a solution?
> > > > 
> > > > 
> > > > Yes, just go to the forked project in my GitHub: https://github.com/fabrizioromanelli/homeassistant-midea-dehumidifier And replace humidifier.py and sensor.py in your home assistant installation with the ones provided on my page, restart HA and it'll work!
> > > 
> > > 
> > > that works mille grazie
> > 
> > 
> > Cant understand why i can get it to work. Please check off any thing is wrong:
> > 
> > 1. Went to the link and downloaded humidifier.py and sensor.py
> > 2. Via samba (on Windows), copied over on my HA installation. (I noticed that new files are much bigger than the original ones)
> > 3. Restarted HA
> 
> Maybe delete all the hacks files and entities and start over. I just used the integration for the first time and with the two new files it worked

Deleted integration and entities. Replaced the 2 files. Still isnt working...

**Comment by ptgomes** [comment] 2024-01-12 13:43
Solved it! 
Installed EVA II PRO WiFi Midea Inventor Dehumidifier custom integration **_V2_**.
And there is no need to replaced the 2 files

**Comment by MrTom1** [comment] 2024-01-12 16:22
> Solved it! Installed EVA II PRO WiFi Midea Inventor Dehumidifier custom integration **_V2_**. And there is no need to replace the 2 files

Where/How to get "V2". I could find only latest 1.4.

**Comment by ptgomes** [comment] 2024-01-13 17:26
> > Solved it! Installed EVA II PRO WiFi Midea Inventor Dehumidifier custom integration **_V2_**. And there is no need to replace the 2 files
> 
> Where/How to get "V2". I could find only latest 1.4.

![Uploading Screenshot_20240113_172439_Home Assistant.jpg…]()

**Comment by friimaind** [comment] 2024-01-14 12:00
I've the same problem as @LeoWinterDE mentioned:

>     Unable to prepare setup for platform 'midea_dehumidifier.sensor': Platform not found (Exception importing custom_components.midea_dehumidifier.sensor).
>    Unable to prepare setup for platform 'midea_dehumidifier.humidifier': Platform not found (Exception importing custom_components.midea_dehumidifier.humidifier).

@ptgomes your screenshot isn't working, where did you find the "V2"?

**Comment by ghenzler** [comment] 2024-01-14 15:44
So I just couldn't make v1.04 from HACS work with latest HA 2024.1.3 - @barban-dev it sounds like you recreated https://github.com/barban-dev/homeassistant-midea-dehumidifier/releases/tag/v1.04 (as it says "patched" in the title) - possibly HACS is caching your old v1.04 somewhere.

> FYI, [HA 2024.1.1](https://www.home-assistant.io/blog/2024/01/03/release-20241/#release-202411---january-5) fixed the backwards compatibility for humidifier supported_features

I ended downgrading to v1.03 - this works for me now (v1.03 with HA 2024.1.3)

**Comment by ptgomes** [comment] 2024-01-14 15:51
> I've the same problem as @LeoWinterDE mentioned:
> 
> > Unable to prepare setup for platform 'midea_dehumidifier.sensor': Platform not found (Exception importing custom_components.midea_dehumidifier.sensor).
> > Unable to prepare setup for platform 'midea_dehumidifier.humidifier': Platform not found (Exception importing custom_components.midea_dehumidifier.humidifier).
> 
> @ptgomes your screenshot isn't working, where did you find the "V2"?

Search on hacs for midea v2

**Comment by maurolemos** [comment] 2024-01-15 13:08
Same issue:

```
Unable to prepare setup for platform 'midea_dehumidifier.sensor': Platform not found (Exception importing custom_components.midea_dehumidifier.sensor).
09:41:14 – (ERROR) setup.py - message first occurred at 09:41:13 and shows up 2 times
Unexpected exception importing platform custom_components.midea_dehumidifier.sensor
09:41:14 – (ERROR) loader.py - message first occurred at 09:41:13 and shows up 2 times
```

Also can't find midea V2 like @ptgomes is suggesting

**Comment by ptgomes** [comment] 2024-01-15 13:14
> Same issue:
> 
> ```
> Unable to prepare setup for platform 'midea_dehumidifier.sensor': Platform not found (Exception importing custom_components.midea_dehumidifier.sensor).
> 09:41:14 – (ERROR) setup.py - message first occurred at 09:41:13 and shows up 2 times
> Unexpected exception importing platform custom_components.midea_dehumidifier.sensor
> 09:41:14 – (ERROR) loader.py - message first occurred at 09:41:13 and shows up 2 times
> ```
> 
> Also can't find midea V2 like @ptgomes is suggesting

![image](https://github.com/barban-dev/homeassistant-midea-dehumidifier/assets/31014473/de228091-22d2-4d0c-9a07-372fb15b1a78)

**Comment by maurolemos** [comment] 2024-01-15 14:10
> > Same issue:
> > ```
> > Unable to prepare setup for platform 'midea_dehumidifier.sensor': Platform not found (Exception importing custom_components.midea_dehumidifier.sensor).
> > 09:41:14 – (ERROR) setup.py - message first occurred at 09:41:13 and shows up 2 times
> > Unexpected exception importing platform custom_components.midea_dehumidifier.sensor
> > 09:41:14 – (ERROR) loader.py - message first occurred at 09:41:13 and shows up 2 times
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also can't find midea V2 like @ptgomes is suggesting
> 
> ![image](https://private-user-images.githubusercontent.com/31014473/296765298-de228091-22d2-4d0c-9a07-372fb15b1a78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjc4MjEsIm5iZiI6MTcwNTMyNzUyMSwicGF0aCI6Ii8zMTAxNDQ3My8yOTY3NjUyOTgtZGUyMjgwOTEtMjJkMi00ZDBjLTlhMDctMzcyZmIxNWIxYTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE0MDUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ODZhYTMwMzQ4OGI4MjFiNTJlYzZiNzA3MGUzZjZlMGM2ZWQ5NGJhYzY1NDVlYTE2MDEzMjYwMzQ1NTk4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBHScbJQbTEzWw1MayHQGq05M0l7fikFu_gwnvV0qis)

Is it coming from a custom repository? If you click on the integration, what does it show here?
<img width="832" alt="Screenshot 2024-01-15 at 14 10 03" src="https://github.com/barban-dev/homeassistant-midea-dehumidifier/assets/35693853/9152ca41-32f6-4009-9bdc-7a5e8cb48558">

**Comment by domerich** [comment] 2024-01-15 16:15
> midea V2

same here, midea V2 does not exist in HACS

**Comment by LeoWinterDE** [comment] 2024-01-17 15:05
> Btw, downgrading to 1.03 fixes the issue with hass 2024.1.3

Yeah this works. Could the patch v1.04 just be reverted?

**Comment by YahyaAlfayad** [comment] 2024-01-17 22:08
I had the same issue when I upgraded and ended up fixing the indentation manually. I am guessing that the problem is with the space character used (sometimes on windows or based on the editor used, the space character differs from the ones used in other lines).

@LeoWinterDE Version 1.03 is working on HA now because they added backwards compatibility for humidifier's supported features but that doesn't mean the change should be reverted. The change makes it compatible with all the future releases of HA even after they completely deprecate the humidifier `supported_features` as iterable.

Try to open `humidifier.py` and `sensor.py` using visual studio code addon on HA and you can easily spot the indentation problem.

**Comment by enricota66** [comment] 2024-01-31 21:27
[You can try this....](https://github.com/barban-dev/homeassistant-midea-dehumidifier/issues/70#issuecomment-1919839229)

**Comment by cannondale0815** [comment] 2024-02-06 14:19
> I had the same issue when I upgraded and ended up fixing the indentation manually. I am guessing that the problem is with the space character used (sometimes on windows or based on the editor used, the space character differs from the ones used in other lines).

I can confirm that 1.04 works after resolving several indentation issues in the code. Thank you!

**Comment by domerich** [comment] 2024-02-26 16:27
> [You can try this....](https://github.com/barban-dev/homeassistant-midea-dehumidifier/issues/70#issuecomment-1919839229)

it works however the humidty entity disappear. I only get the control entity

**Comment by cannondale0815** [comment] 2024-08-07 03:12
Seems like version 1.04 again broke in HA 2024.7.4:

`
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 9:07:46 PM (1 occurrences)
Last logged: 9:07:46 PM

Error during setup of component midea_dehumidifier
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/midea_dehumidifier/__init__.py", line 66, in async_setup
    res = await hass.async_add_executor_job(client.login)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midea_inventor_lib/midea_client.py", line 69, in login
    response = self.__api_request("/v1/user/login/id/get", {"loginAccount": self.email})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midea_inventor_lib/midea_client.py", line 585, in __api_request
    response = self.__send_api_request(path, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midea_inventor_lib/midea_client.py", line 596, in __send_api_request
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by barban-dev** [comment] 2024-08-31 18:12
it sounds like you recreated https://github.com/barban-dev/homeassistant-midea-dehumidifier/releases/tag/v1.04 (as it says "patched" in the title) - possibly HACS is caching your old v1.04 somewhere.

Yep, I think this was the reason for the issues reported here.

**Comment by barban-dev** [comment] 2024-08-31 18:13
v 1.05 is coming out...

**Closed by barban-dev** 2024-08-31 18:13 UTC
