### ISSUE TITLE
Breaking change for ATTR_MODE on 2021.4

### ISSUE THREAD

**Issue by drthanwho** [barban-dev/homeassistant-midea-dehumidifier#21] opened 2021-04-01 10:46 UTC
Running on the beta already and I can see that there will be a change in 2021.4 regarding `homeassistant.components.humidifier.const`. ATTR_MODE was removed, which leads to a breaking change as the integration is unable to import it and completely unable to setup.

```
2021-04-01 03:53:39 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform midea_dehumidifier.humidifier: Platform not found (cannot import name 'ATTR_MODE' from 'homeassistant.components.humidifier.const' (/usr/src/homeassistant/homeassistant/components/humidifier/const.py)).
```

**Comment by arcangelweb** [comment] 2021-04-04 17:46
Its modification for version 2021.4, it works correctly for me. Thanks @drthanwho

**Comment by ledrexter** [comment] 2021-04-05 17:34
Hi Thanasis,

so what's the fix for this issue?
I have the same error for the last 4-5 days but I still cannot get rid of the issue.

Regards,
Petar

**Comment by arcangelweb** [comment] 2021-04-05 17:37
@ledrexter if you follow the links, you can download a modified file.

https://github.com/barban-dev/homeassistant-midea-dehumidifier/pull/22/commits/42a8195c5d5a5a6783c738af480873d8292b1fa2

**Comment by drthanwho** [comment] 2021-04-05 17:37
@ledrexter look at the pull request I've linked. You can edit that file yourself manually for now till @barban-dev fixes the issue

**Comment by ledrexter** [comment] 2021-04-05 18:06
Hi @arcangelweb and @drthanwho,

thanks a lot for you fast response.
I now see the fix in the humidifier.py and the issue is gone after applying it!

Kind regards,
Petar

**Closed** 2021-04-11 19:57 UTC
